CREATE TABLE COMMENT_MASTER 
(
  COMMENT_ID NUMBER(15, 0) NOT NULL 
, PAGE_PATH VARCHAR2(250 BYTE) NOT NULL 
, MAX_NO_OF_COMMENTS NUMBER(5, 0) DEFAULT 20 NOT NULL 
, MAX_SUB_COMMENT_LEVEL NUMBER(5, 0) DEFAULT 0 NOT NULL 
, ENFORCE_PATH_VALIDATION CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, LAST_MOD_DATE DATE DEFAULT SYSDATE NOT NULL 
, LAST_MOD_USER_ID CHAR(6 BYTE) NOT NULL 
, CONSTRAINT COMMENT_MASTER_PK PRIMARY KEY 
  (
    COMMENT_ID 
  )
  
   CREATE TABLE COMMENT_ENTRY 
   (
	COMMENT_ENTRY_SID NUMBER(15,0)
	COMMENT_REF_ID NUMBER(15,0), 
	COMMENT_ENTRY_ID NUMBER(15,0), 
	PARENT_ENTRY_ID NUMBER(15,0), 
	STATUS_ID NUMBER(15,0), 
	COMMENT_TEXT VARCHAR2(250 BYTE), 
	POSTED_USER_ID VARCHAR2(100 BYTE) DEFAULT 'Anonymous', 
	POSTED_USER_NAME VARCHAR2(100 BYTE), 
	POSTED_USER_EMAIL VARCHAR2(150 BYTE), 
	POSTED_DATE_TIME DATE, 
	DELETED_DATE_TIME DATE, 
	APPROVER_USER_ID CHAR(6 BYTE), 
	APPROVED_OR_REJECTED_DATE_TIME DATE, 
	LAST_MOD_USER_ID VARCHAR2(100 BYTE)
   )
   
  ALTER TABLE COMMENT_ENTRY ADD CONSTRAINT COMMENT_ENTRY_PK PRIMARY KEY (COMMENT_ENTRY_SID)
  ALTER TABLE COMMENT_ENTRY MODIFY (LAST_MOD_USER_ID NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (POSTED_DATE_TIME NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (POSTED_USER_ID NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (COMMENT_TEXT NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (STATUS_ID NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (COMMENT_ENTRY_ID NOT NULL ENABLE);
  ALTER TABLE COMMENT_ENTRY MODIFY (COMMENT_REF_ID NOT NULL ENABLE);

  ALTER TABLE COMMENT_ENTRY ADD CONSTRAINT COMMENT_ENTRY_1 FOREIGN KEY (COMMENT_REF_ID)
	  REFERENCES COMMENT_MASTER (COMMENT_ID) ENABLE;
  ALTER TABLE COMMENT_ENTRY ADD CONSTRAINT COMMENT_ENTRY_2 FOREIGN KEY (STATUS_ID)
	  REFERENCES COMMENT_STATUS (STATUS_ID) ENABLE;
	  
  CREATE TABLE COMMENT_STATUS 
   (	STATUS_ID NUMBER(5,0), 
	STATUS_DISCRIPTION VARCHAR2(100 BYTE)
   ) 
  ALTER TABLE COMMENT_STATUS ADD CONSTRAINT COMMENT_STATUS_PK PRIMARY KEY (STATUS_ID)
  ALTER TABLE COMMENT_STATUS MODIFY (STATUS_DISCRIPTION NOT NULL ENABLE);
  ALTER TABLE COMMENT_STATUS MODIFY (STATUS_ID NOT NULL ENABLE);